In [1]:
from src.param_parser import parameter_parser
from collections import defaultdict
import json
import random
import networkx as nx
import numpy as np
import torch

from src.gam import GAMTrainer, GAM
from src.utils import create_features

ModuleNotFoundError: No module named 'src.param_parser'

In [2]:
class ARGS(object):
    def __init__(self):
        self.train_graph_folder = './input/train/'
        self.test_graph_folder = './input/test/'
        self.prediction_path = './output/erdos_predictions.csv'
        self.log_path = './logs/erdos_gam_logs.json'
        self.epochs = 30
        self.step_dimensions = 32 # size of first dimension of StepNetworkLayer's (step_block) theta vectors
        self.combined_dimensions = 64 # size of DownStreamNetworkLayer's (down_block) hidden state
        self.batch_size = 10
        self.time = 10 # maximum number of steps that agent can take (time budget)
        self.repetitions = 10 # number of agents exploring?
        self.gamma = 0.99 # decay factor in scoring
        self.learning_rate = 1e-3
        self.weight_decay = 0 # weight regularization; usually doesn't help

In [17]:
x = torch.Tensor(5,5).normal_(0,1)
x += x.clone().transpose(1,0)
x = torch.where(x > 0, 1, 0)
x

tensor([[1, 1, 0, 1, 1],
        [1, 1, 1, 1, 0],
        [0, 1, 0, 1, 0],
        [1, 1, 1, 1, 0],
        [1, 0, 0, 0, 0]])

In [56]:
test = dict(zip([str(n) for n in range(5)], x.sum(dim=0).numpy()))
test

{'0': 4, '1': 4, '2': 2, '3': 4, '4': 1}

In [83]:
inv_test = {}
for k, v in test.items():
    if str(v) in inv_test.keys(): inv_test[str(v)].add(int(k))
    else: inv_test[str(v)] = {int(k)}
inv_test

{'4': {0, 1, 3}, '2': {2}, '1': {4}}

In [3]:
args = ARGS()

model = GAMTrainer(args)
model.fit()
model.score()

100%|██████████| 100/100 [00:00<00:00, 5149.23it/s]




The number of graph classes is: 3.


Training started.



Epoch:   0%|          | 0/30 [00:00<?, ?it/s]

lstm_output shape: torch.Size([1, 1, 64])
LSTM.h0 shape: torch.Size([1, 1, 64])
LSTM.c0 shape: torch.Size([1, 1, 64])
tensor(True) tensor(False)
h shape: torch.Size([1, 1, 64])
h.view(1,-1) shape: torch.Size([1, 64])
theta_classification shape: torch.Size([64, 3])
theta_rank shape: torch.Size([64, 24])
lstm_output shape: torch.Size([1, 1, 64])
LSTM.h0 shape: torch.Size([1, 1, 64])
LSTM.c0 shape: torch.Size([1, 1, 64])
tensor(True) tensor(False)
h shape: torch.Size([1, 1, 64])
h.view(1,-1) shape: torch.Size([1, 64])
theta_classification shape: torch.Size([64, 3])
theta_rank shape: torch.Size([64, 24])
lstm_output shape: torch.Size([1, 1, 64])
LSTM.h0 shape: torch.Size([1, 1, 64])
LSTM.c0 shape: torch.Size([1, 1, 64])
tensor(True) tensor(False)
h shape: torch.Size([1, 1, 64])
h.view(1,-1) shape: torch.Size([1, 64])
theta_classification shape: torch.Size([64, 3])
theta_rank shape: torch.Size([64, 24])
lstm_output shape: torch.Size([1, 1, 64])
LSTM.h0 shape: torch.Size([1, 1, 64])
LSTM.c0 

lstm_output shape: torch.Size([1, 1, 64])
LSTM.h0 shape: torch.Size([1, 1, 64])
LSTM.c0 shape: torch.Size([1, 1, 64])
tensor(True) tensor(False)
h shape: torch.Size([1, 1, 64])
h.view(1,-1) shape: torch.Size([1, 64])
theta_classification shape: torch.Size([64, 3])
theta_rank shape: torch.Size([64, 24])
lstm_output shape: torch.Size([1, 1, 64])
LSTM.h0 shape: torch.Size([1, 1, 64])
LSTM.c0 shape: torch.Size([1, 1, 64])
tensor(True) tensor(False)
h shape: torch.Size([1, 1, 64])
h.view(1,-1) shape: torch.Size([1, 64])
theta_classification shape: torch.Size([64, 3])
theta_rank shape: torch.Size([64, 24])
lstm_output shape: torch.Size([1, 1, 64])
LSTM.h0 shape: torch.Size([1, 1, 64])
LSTM.c0 shape: torch.Size([1, 1, 64])
tensor(True) tensor(False)
h shape: torch.Size([1, 1, 64])
h.view(1,-1) shape: torch.Size([1, 64])
theta_classification shape: torch.Size([64, 3])
theta_rank shape: torch.Size([64, 24])
lstm_output shape: torch.Size([1, 1, 64])
LSTM.h0 shape: torch.Size([1, 1, 64])
LSTM.c0 

lstm_output shape: torch.Size([1, 1, 64])
LSTM.h0 shape: torch.Size([1, 1, 64])
LSTM.c0 shape: torch.Size([1, 1, 64])
tensor(True) tensor(False)
h shape: torch.Size([1, 1, 64])
h.view(1,-1) shape: torch.Size([1, 64])
theta_classification shape: torch.Size([64, 3])
theta_rank shape: torch.Size([64, 24])
lstm_output shape: torch.Size([1, 1, 64])
LSTM.h0 shape: torch.Size([1, 1, 64])
LSTM.c0 shape: torch.Size([1, 1, 64])
tensor(True) tensor(False)
h shape: torch.Size([1, 1, 64])
h.view(1,-1) shape: torch.Size([1, 64])
theta_classification shape: torch.Size([64, 3])
theta_rank shape: torch.Size([64, 24])
lstm_output shape: torch.Size([1, 1, 64])
LSTM.h0 shape: torch.Size([1, 1, 64])
LSTM.c0 shape: torch.Size([1, 1, 64])
tensor(True) tensor(False)
h shape: torch.Size([1, 1, 64])
h.view(1,-1) shape: torch.Size([1, 64])
theta_classification shape: torch.Size([64, 3])
theta_rank shape: torch.Size([64, 24])
lstm_output shape: torch.Size([1, 1, 64])
LSTM.h0 shape: torch.Size([1, 1, 64])
LSTM.c0 

Epoch:   3%|▎         | 1/30 [00:00<00:11,  2.61it/s]

lstm_output shape: torch.Size([1, 1, 64])
LSTM.h0 shape: torch.Size([1, 1, 64])
LSTM.c0 shape: torch.Size([1, 1, 64])
tensor(True) tensor(False)
h shape: torch.Size([1, 1, 64])
h.view(1,-1) shape: torch.Size([1, 64])
theta_classification shape: torch.Size([64, 3])
theta_rank shape: torch.Size([64, 24])
lstm_output shape: torch.Size([1, 1, 64])
LSTM.h0 shape: torch.Size([1, 1, 64])
LSTM.c0 shape: torch.Size([1, 1, 64])
tensor(True) tensor(False)
h shape: torch.Size([1, 1, 64])
h.view(1,-1) shape: torch.Size([1, 64])
theta_classification shape: torch.Size([64, 3])
theta_rank shape: torch.Size([64, 24])
lstm_output shape: torch.Size([1, 1, 64])
LSTM.h0 shape: torch.Size([1, 1, 64])
LSTM.c0 shape: torch.Size([1, 1, 64])
tensor(True) tensor(False)
h shape: torch.Size([1, 1, 64])
h.view(1,-1) shape: torch.Size([1, 64])
theta_classification shape: torch.Size([64, 3])
theta_rank shape: torch.Size([64, 24])
lstm_output shape: torch.Size([1, 1, 64])
LSTM.h0 shape: torch.Size([1, 1, 64])
LSTM.c0 

lstm_output shape: torch.Size([1, 1, 64])
LSTM.h0 shape: torch.Size([1, 1, 64])
LSTM.c0 shape: torch.Size([1, 1, 64])
tensor(True) tensor(False)
h shape: torch.Size([1, 1, 64])
h.view(1,-1) shape: torch.Size([1, 64])
theta_classification shape: torch.Size([64, 3])
theta_rank shape: torch.Size([64, 24])
lstm_output shape: torch.Size([1, 1, 64])
LSTM.h0 shape: torch.Size([1, 1, 64])
LSTM.c0 shape: torch.Size([1, 1, 64])
tensor(True) tensor(False)
h shape: torch.Size([1, 1, 64])
h.view(1,-1) shape: torch.Size([1, 64])
theta_classification shape: torch.Size([64, 3])
theta_rank shape: torch.Size([64, 24])
lstm_output shape: torch.Size([1, 1, 64])
LSTM.h0 shape: torch.Size([1, 1, 64])
LSTM.c0 shape: torch.Size([1, 1, 64])
tensor(True) tensor(False)
h shape: torch.Size([1, 1, 64])
h.view(1,-1) shape: torch.Size([1, 64])
theta_classification shape: torch.Size([64, 3])
theta_rank shape: torch.Size([64, 24])
lstm_output shape: torch.Size([1, 1, 64])
LSTM.h0 shape: torch.Size([1, 1, 64])
LSTM.c0 

lstm_output shape: torch.Size([1, 1, 64])
LSTM.h0 shape: torch.Size([1, 1, 64])
LSTM.c0 shape: torch.Size([1, 1, 64])
tensor(True) tensor(False)
h shape: torch.Size([1, 1, 64])
h.view(1,-1) shape: torch.Size([1, 64])
theta_classification shape: torch.Size([64, 3])
theta_rank shape: torch.Size([64, 24])
lstm_output shape: torch.Size([1, 1, 64])
LSTM.h0 shape: torch.Size([1, 1, 64])
LSTM.c0 shape: torch.Size([1, 1, 64])
tensor(True) tensor(False)
h shape: torch.Size([1, 1, 64])
h.view(1,-1) shape: torch.Size([1, 64])
theta_classification shape: torch.Size([64, 3])
theta_rank shape: torch.Size([64, 24])
lstm_output shape: torch.Size([1, 1, 64])
LSTM.h0 shape: torch.Size([1, 1, 64])
LSTM.c0 shape: torch.Size([1, 1, 64])
tensor(True) tensor(False)
h shape: torch.Size([1, 1, 64])
h.view(1,-1) shape: torch.Size([1, 64])
theta_classification shape: torch.Size([64, 3])
theta_rank shape: torch.Size([64, 24])
lstm_output shape: torch.Size([1, 1, 64])
LSTM.h0 shape: torch.Size([1, 1, 64])
LSTM.c0 

lstm_output shape: torch.Size([1, 1, 64])
LSTM.h0 shape: torch.Size([1, 1, 64])
LSTM.c0 shape: torch.Size([1, 1, 64])
tensor(True) tensor(False)
h shape: torch.Size([1, 1, 64])
h.view(1,-1) shape: torch.Size([1, 64])
theta_classification shape: torch.Size([64, 3])
theta_rank shape: torch.Size([64, 24])
lstm_output shape: torch.Size([1, 1, 64])
LSTM.h0 shape: torch.Size([1, 1, 64])
LSTM.c0 shape: torch.Size([1, 1, 64])
tensor(True) tensor(False)
h shape: torch.Size([1, 1, 64])
h.view(1,-1) shape: torch.Size([1, 64])
theta_classification shape: torch.Size([64, 3])
theta_rank shape: torch.Size([64, 24])
lstm_output shape: torch.Size([1, 1, 64])
LSTM.h0 shape: torch.Size([1, 1, 64])
LSTM.c0 shape: torch.Size([1, 1, 64])
tensor(True) tensor(False)
h shape: torch.Size([1, 1, 64])
h.view(1,-1) shape: torch.Size([1, 64])
theta_classification shape: torch.Size([64, 3])
theta_rank shape: torch.Size([64, 24])
lstm_output shape: torch.Size([1, 1, 64])
LSTM.h0 shape: torch.Size([1, 1, 64])
LSTM.c0 

Epoch:   3%|▎         | 1/30 [00:00<00:19,  1.46it/s]


lstm_output shape: torch.Size([1, 1, 64])
LSTM.h0 shape: torch.Size([1, 1, 64])
LSTM.c0 shape: torch.Size([1, 1, 64])
tensor(True) tensor(False)
h shape: torch.Size([1, 1, 64])
h.view(1,-1) shape: torch.Size([1, 64])
theta_classification shape: torch.Size([64, 3])
theta_rank shape: torch.Size([64, 24])
lstm_output shape: torch.Size([1, 1, 64])
LSTM.h0 shape: torch.Size([1, 1, 64])
LSTM.c0 shape: torch.Size([1, 1, 64])
tensor(True) tensor(False)
h shape: torch.Size([1, 1, 64])
h.view(1,-1) shape: torch.Size([1, 64])
theta_classification shape: torch.Size([64, 3])
theta_rank shape: torch.Size([64, 24])
lstm_output shape: torch.Size([1, 1, 64])
LSTM.h0 shape: torch.Size([1, 1, 64])
LSTM.c0 shape: torch.Size([1, 1, 64])
tensor(True) tensor(False)
h shape: torch.Size([1, 1, 64])
h.view(1,-1) shape: torch.Size([1, 64])
theta_classification shape: torch.Size([64, 3])
theta_rank shape: torch.Size([64, 24])
lstm_output shape: torch.Size([1, 1, 64])
LSTM.h0 shape: torch.Size([1, 1, 64])
LSTM.c0 

KeyboardInterrupt: 

In [11]:
data_tr1 = json.load(open('./input/train/1.json'))
data_tr1.keys()

dict_keys(['target', 'edges', 'labels', 'inverse_labels'])

In [6]:
G = nx.Graph()
G.add_edges_from(data_tr1['edges'])

In [8]:
G.nodes()

NodeView((0, 1, 4, 7, 11, 31, 32, 48, 55, 58, 77, 88, 98, 16, 35, 38, 54, 59, 78, 90, 97, 2, 15, 25, 33, 60, 69, 71, 3, 6, 21, 37, 40, 68, 99, 13, 93, 5, 26, 51, 80, 84, 12, 81, 85, 94, 44, 47, 57, 64, 70, 76, 8, 9, 20, 29, 34, 96, 62, 74, 10, 24, 73, 89, 28, 43, 63, 67, 22, 23, 27, 45, 17, 52, 14, 46, 49, 83, 87, 50, 66, 91, 95, 18, 42, 72, 19, 30, 39, 92, 53, 41, 61, 75, 36, 82, 79, 86, 56, 65))

In [10]:
nx.adjacency_matrix(G).todense()

array([[0, 1, 1, ..., 0, 0, 0],
       [1, 0, 1, ..., 0, 0, 0],
       [1, 1, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [12]:
H = nx.Graph()
H.add_nodes_from(sorted(G.nodes()))
H.add_edges_from(data_tr1['edges'])

In [19]:
(
    nx.adjacency_matrix(G).todense() 
    == nx.adjacency_matrix(H).todense()[G.nodes(), :][:, G.nodes()] 
).all() # sort rows ?

True

In [ ]:
# figure out stupid JSON loading logic

args = ARGS()
trainer = GAMTrainer(args=args)

# understanding process_graph
# 1. get dictionary with keys (target, edges, labels, inverse_labels), values as expected
data = json.load(open(trainer.training_graphs[0]))
# 2. create_features produces a NetworkX graph with its node features
# features is a 2D tensor of one-hot labels for each node in graph (see create_features)
graph, features = create_features(data, trainer.model.identifiers)
# 3. pick a random node
node = random.choice(list(graph.nodes))
attention_loss = 0
# 4. iterate for some time (limited by budget)
for t in range(args.time):
    # 5. call forward pass of GAM
    predictions, node, attention_score = trainer.model(data, graph, features, node)
    # in forward call of GAM, only instance of graph is the forward call to GAM.step_block (type: StepNetworkLayer)
    # in forward call of GAM.step_block, graph only appears in step_block.make_step
    # in call to make_step, two NetworkX functions are used:
        # nx.neighbors
            # can be replaced by torch.where(adj[node_id])?
        # in step_block.sample_node_labels, which needs graph.nodes
            # can be replaced by torch.range(adj.shape[0])?


In [ ]:
# understanding create_features

identifiers = [1]
# 1. make networkx graph without features 
# can be replaced with filling in a torch tensor of zeros
graph = nx.from_edgelist(data["edges"])
# 2. fill in node feature matrix
# features are one-hot vectors - not sure how important a feature matrix is, but we can possibly
# replace it with a vector of one's whose length is the number of nodes (same as only having one
# label)
features = []
for node in graph.nodes():
    features.append([1.0 if data["labels"][str(node)] == i else 0.0 for i in range(len(identifiers))])
# 3. features cast to np.array and then torch.Tensor
# features = np.array(features, dtype=np.float32)
features = torch.tensor(features)

In [ ]:
# understanding process_batch
# typical training loop

In [ ]:
# understanding fit
# instead of manually creating batches, we use procecss_batch, but otherwise there's no strange logic I see

In [ ]:
trainer.training_graphs

['./input/train/20.json',
 './input/train/36.json',
 './input/train/41.json',
 './input/train/16.json',
 './input/train/6.json',
 './input/train/7.json',
 './input/train/17.json',
 './input/train/40.json',
 './input/train/37.json',
 './input/train/21.json',
 './input/train/47.json',
 './input/train/10.json',
 './input/train/26.json',
 './input/train/30.json',
 './input/train/31.json',
 './input/train/27.json',
 './input/train/1.json',
 './input/train/50.json',
 './input/train/11.json',
 './input/train/46.json',
 './input/train/2.json',
 './input/train/28.json',
 './input/train/12.json',
 './input/train/45.json',
 './input/train/32.json',
 './input/train/24.json',
 './input/train/49.json',
 './input/train/48.json',
 './input/train/25.json',
 './input/train/33.json',
 './input/train/44.json',
 './input/train/13.json',
 './input/train/29.json',
 './input/train/3.json',
 './input/train/34.json',
 './input/train/8.json',
 './input/train/22.json',
 './input/train/18.json',
 './input/train/38

In [ ]:
data

{'target': 2,
 'edges': [[0, 2],
  [0, 4],
  [0, 6],
  [0, 24],
  [0, 29],
  [0, 34],
  [0, 43],
  [0, 45],
  [0, 49],
  [0, 54],
  [0, 80],
  [1, 40],
  [1, 62],
  [1, 63],
  [1, 66],
  [1, 71],
  [1, 74],
  [1, 77],
  [1, 93],
  [1, 94],
  [1, 97],
  [2, 6],
  [2, 7],
  [2, 13],
  [2, 23],
  [2, 28],
  [2, 36],
  [2, 37],
  [2, 41],
  [2, 65],
  [2, 67],
  [2, 69],
  [2, 85],
  [2, 92],
  [3, 19],
  [3, 27],
  [3, 43],
  [3, 48],
  [3, 52],
  [3, 60],
  [3, 62],
  [3, 64],
  [3, 68],
  [3, 76],
  [3, 78],
  [3, 88],
  [3, 89],
  [4, 32],
  [4, 37],
  [4, 49],
  [4, 62],
  [4, 75],
  [4, 76],
  [4, 83],
  [4, 84],
  [4, 86],
  [4, 96],
  [5, 18],
  [5, 20],
  [5, 38],
  [5, 41],
  [5, 44],
  [5, 49],
  [5, 68],
  [5, 69],
  [5, 75],
  [5, 76],
  [5, 95],
  [6, 9],
  [6, 28],
  [6, 33],
  [6, 34],
  [6, 40],
  [6, 49],
  [6, 60],
  [6, 62],
  [6, 64],
  [6, 65],
  [6, 70],
  [6, 82],
  [6, 95],
  [6, 96],
  [7, 20],
  [7, 26],
  [7, 27],
  [7, 37],
  [7, 42],
  [7, 48],
  [7, 58],
  [7

In [ ]:
# load all JSON graphs at once here
# then replace GAMTrainer.training_graphs, or whatever the appropriate structure is, with Tensors (adj and feats)
# then modify GAM code 

adj_lst, feat_lst = [], [] # lists of adjacency matrices and features; i-th entry has i-th adj/feat
for graph_path in trainer.training_graphs:
    data = json.load(open(graph_path))
    graph, feat = create_features(data, trainer.model.identifiers)
    adj = torch.Tensor(nx.adjacency_matrix(graph).todense())
    adj_lst.append(adj), feat_lst.append(feat)

In [ ]:
torch.Tensor(graph.nodes()).int().sort()

torch.return_types.sort(
values=tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
        36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53,
        54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71,
        72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89,
        90, 91, 92, 93, 94, 95, 96, 97, 98, 99], dtype=torch.int32),
indices=tensor([ 0, 15, 27, 28, 42, 29, 56, 63, 57, 30, 75, 16, 43, 58, 85,  1,  2, 72,
        91, 17, 73,  3, 37, 38, 67, 50,  4,  5, 59, 95, 18, 86, 64, 92, 19, 68,
        20, 76, 51, 31, 44, 32, 77, 99, 21, 33, 84, 60, 69,  6, 61, 93, 22, 23,
        34, 39, 87, 62, 24, 88, 52, 89, 35, 70, 80,  7, 98, 74,  8, 45, 40, 65,
         9, 71, 10, 41, 46, 78, 47, 53, 90, 96, 11, 12, 36, 94, 81, 54, 48, 25,
        97, 49, 13, 14, 79, 82, 26, 55, 66, 83]))

In [ ]:
torch.Tensor(nx.adjacency_matrix(graph).todense()).int().shape

torch.Size([100, 100])

In [ ]:
torch.nonzero(torch.Tensor(range(4)).int())

tensor([[1],
        [2],
        [3]])

In [ ]:
label_predictions, node, attention_score = trainer.model(data, graph, feat, 0) 
label_predictions = torch.nn.Softmax(dim=1)(label_predictions)
label_predictions, node, attention_score 
# instances of graph need to be fixed to not use networkx functions
# NOTE: assume networkx graph has been replaced by adjacency matrix in torch.Tensor form

(tensor([[0.4648, 0.2727, 0.2625]], grad_fn=<SoftmaxBackward0>),
 65,
 tensor(0.0533, grad_fn=<SelectBackward0>))

In [ ]:
model = GAMTrainer(args)
model.fit()
model.score()

100%|██████████| 50/50 [00:00<00:00, 4775.15it/s]




The number of graph classes is: 3.


Training started.



Epoch:   0%|          | 0/10 [00:00<?, ?it/s]

nodes: tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
        36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53,
        54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71,
        72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89,
        90, 91, 92, 93, 94, 95, 96, 97, 98, 99], dtype=torch.int32)
neighbor_vector: tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.])
neighbor_features: tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,

ValueError: probabilities contain NaN

In [ ]:
torch.Tensor([4]).item()

4.0